apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Monitoring project
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - 'https://github.com/farru1998/gitops.git'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: monitoring
    server: https://kubernetes.default.svc
  # Deny all cluster-scoped resources from be