apiVersion: v2
name: my-grafana-app
description: A Helm chart for deploying Grafana
type: application
version: 8.4.8
dependencies:
  - name: grafana
    version: 8.4.8
    repository: "https://grafana.github.io/helm-charts"