apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd  # Change this to your ArgoCD namespace if different
spec:
  project: monitoring
  source:
    repoURL: https://github.com/farru1998/gitops.git
    path: charts/grafana
    helm:
      valueFiles:
        - manifest/grafana/values.yaml
  destination:
    server: https://kubernetes.default.svc  # Kubernetes API server URL
    namespace: monitoring  # Target namespace for Grafana deployment